### ISSUE TITLE
.gitconfig is empty

### ISSUE THREAD

**Issue by wtty-fool** [wtty-fool/cozy#9]
As of now the `.gitconfig` file is empty. It needs some content e.g. 
+ sane defaults for `git alias`
+ `--simple` flag for `pull`
+ _vim_ as default editor
+ colored log

**Comment by sultrytsardine** [comment]
@wtty-fool is this issue still available?

**Comment by wtty-fool** [comment]
@sultrytsardine it is

**Comment by sultrytsardine** [comment]
Great, I'll have a go at it

**Comment by sultrytsardine** [comment]
Hi @wtty-fool , I don't seem to have the permission to push to this repo, do I need write access?

**Comment by wtty-fool** [comment]
No, you don't need it. You need to raise a pull request with the changes.
1. fork this repository
2. make changes in your own repository
3. make a pull request to this repository, selecting my _master_ branch as base
4. I review and accept the pull request
That's how it's done 😄

**Comment by sultrytsardine** [comment]
Cheers. I have raised a pull request, let me know if this is what you're after
https://github.com/wtty-fool/cozy/pull/10

**Comment by wtty-fool** [comment]
Resolved by #10
